---
title: InternalError.prototype
slug: conflicting/Web/JavaScript/Reference/Global_Objects/InternalError
tags:
  - Error
  - InternalError
  - JavaScript
  - Non-standard
  - Property
translation_of: Web/JavaScript/Reference/Global_Objects/InternalError
translation_of_original: Web/JavaScript/Reference/Global_Objects/InternalError/prototype
original_slug: Web/JavaScript/Reference/Global_Objects/InternalError/prototype
---
<div>{{JSRef("Global_Objects", "Error", "EvalError,InternalError,RangeError,ReferenceError,SyntaxError,TypeError,URIError")}} {{non-standard_header}}</div>

<h2 id="Summary" name="Summary">Сводка</h2>
<p>Свойство <code><strong>InternalError.prototype</strong></code> представляет прототип конструктора объекта {{jsxref("InternalError")}}.</p>

<div>{{js_property_attributes(0, 0, 0)}}</div>

<h2 id="Description" name="Description">Описание</h2>
<p>Все экземпляры {{jsxref("InternalError")}} наследуются от объекта <code>InternalError.prototype</code>. Вы можете использовать прототип для добавления свойств или методов ко всем экземплярам.</p>

<h2 id="Properties" name="Properties">Свойства</h2>
<dl>
 <dt><code>InternalError.prototype.constructor</code></dt>
 <dd>Определяет функцию, создающую прототип экземпляра.</dd>
 <dt>{{jsxref("Error.prototype.message", "InternalError.prototype.message")}}</dt>
 <dd>Сообщение ошибки. Унаследовано от {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.name", "InternalError.prototype.name")}}</dt>
 <dd>Название ошибки. Унаследовано от {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.fileName", "InternalError.prototype.fileName")}}</dt>
 <dd>Путь к файлу, в котором возникла эта ошибка. Унаследовано от {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.lineNumber", "InternalError.prototype.lineNumber")}}</dt>
 <dd>Номер строки в файле, в котором возникла эта ошибка. Унаследовано от {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.columnNumber", "InternalError.prototype.columnNumber")}}</dt>
 <dd>Номер колонки в строке, на которой возникла эта ошибка. Унаследовано от {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.stack", "InternalError.prototype.stack")}}</dt>
 <dd>Стек вызовов. Унаследовано от {{jsxref("Error")}}.</dd>
</dl>

<h2 id="Methods" name="Methods">Методы</h2>
<p>Хотя объект прототипа {{jsxref("InternalError")}} не содержит собственных методов, экземпляры {{jsxref("InternalError")}} наследуют некоторые методы из цепочки прототипов.</p>

<h2 id="Specifications" name="Specifications">Спецификации</h2>
<p>Не является частью какой-либо спецификации.</p>

<h2 id="Browser_compatibility" name="Browser_compatibility">Совместимость с браузерами</h2>
<div>{{CompatibilityTable}}</div>
<div id="compat-desktop">
 <table class="compat-table">
  <tbody>
   <tr>
    <th>Возможность</th>
    <th>Chrome</th>
    <th>Firefox (Gecko)</th>
    <th>Internet Explorer</th>
    <th>Opera</th>
    <th>Safari</th>
   </tr>
   <tr>
    <td>Базовая поддержка</td>
    <td>{{CompatNo}}</td>
    <td>{{CompatVersionUnknown}}</td>
    <td>{{CompatNo}}</td>
    <td>{{CompatNo}}</td>
    <td>{{CompatNo}}</td>
   </tr>
  </tbody>
 </table>
</div>
<div id="compat-mobile">
 <table class="compat-table">
  <tbody>
   <tr>
    <th>Возможность</th>
    <th>Android</th>
    <th>Chrome для Android</th>
    <th>Firefox Mobile (Gecko)</th>
    <th>IE Mobile</th>
    <th>Opera Mobile</th>
    <th>Safari Mobile</th>
   </tr>
   <tr>
    <td>Базовая поддержка</td>
    <td>{{CompatNo}}</td>
    <td>{{CompatNo}}</td>
    <td>{{CompatVersionUnknown}}</td>
    <td>{{CompatNo}}</td>
    <td>{{CompatNo}}</td>
    <td>{{CompatNo}}</td>
   </tr>
  </tbody>
 </table>
</div>

<h2 id="See_also" name="See_also">Смотрите также</h2>
<ul>
 <li>{{jsxref("Error.prototype")}}</li>
 <li>{{jsxref("Function.prototype")}}</li>
</ul>
